version: '3.7'

services:
  reforca-api:
    container_name: reforca-api
    image: reforca-api:dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4444:4444
    command: npm run start:dev
    environment:
      NODE_ENV: development
      SERVER_PORT: 4444
      DB_DATABASE: reforca
      DB_CONNECTION_STRING: mongodb://reforca_root:j5m966qp7jiypfda@reforca-mongo:27017
      # DB_CONNECTION_STRING: mysql://reforca_root:j5m966qp7jiypfda@reforca-mysql:3306
    networks:
      - reforca-connect

  reforca-mongo:
    container_name: reforca-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: reforca_root
      MONGO_INITDB_ROOT_PASSWORD: j5m966qp7jiypfda
      MONGO_INITDB_DATABASE: reforca
    ports:
      - 27017:27017
    volumes:
      - ~/docker/volumes/ReforcaApi_MongoDB:/data/db
    networks:
      - reforca-connect
    logging:
      driver: none

  reforca-mysql:
    container_name: reforca-mysql
    image: mysql
    environment:
      MYSQL_USER: reforca_root
      MYSQL_PASSWORD: j5m966qp7jiypfda
      MYSQL_ROOT_PASSWORD: m45ug42qkr5pdzbb
      MYSQL_DATABASE: reforca
    ports:
      - 3306:3306
    volumes:
      - ~/docker/volumes/reforcaApi_MySQL:/var/lib/mysql
    networks:
      - reforca-connect
    logging:
      driver: none

networks:
  reforca-connect:
    driver: bridge
